"""add_folder_and_update_file

Revision ID: 0cb1cd51d0b5
Revises: 0003_add_file_language
Create Date: 2026-09-09 15:49:17.483028
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0cb1cd51d0b5'
down_revision: str | None = '0003_add_file_language'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_parent_folder_id'), 'folders', ['parent_folder_id'], unique=False)
    op.create_index(op.f('ix_folders_project_id'), 'folders', ['project_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_project_id'), 'invitations', ['project_id'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.drop_index('ix_ai_assistant_configs_session_id', table_name='ai_assistant_configs')
    op.add_column('ai_assistant_requests', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.drop_index('ix_ai_assistant_requests_created_at', table_name='ai_assistant_requests')
    op.drop_index('ix_ai_assistant_requests_session_id', table_name='ai_assistant_requests')
    op.drop_index('ix_ai_assistant_requests_user_id', table_name='ai_assistant_requests')
    op.alter_column('debug_sessions', 'execution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('files', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_files_folder_id'), 'files', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'files', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_index(op.f('ix_files_folder_id'), table_name='files')
    op.drop_column('files', 'folder_id')
    op.alter_column('debug_sessions', 'execution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_ai_assistant_requests_user_id', 'ai_assistant_requests', ['user_id'], unique=False)
    op.create_index('ix_ai_assistant_requests_session_id', 'ai_assistant_requests', ['session_id'], unique=False)
    op.create_index('ix_ai_assistant_requests_created_at', 'ai_assistant_requests', ['created_at'], unique=False)
    op.drop_column('ai_assistant_requests', 'prompt_tokens')
    op.create_index('ix_ai_assistant_configs_session_id', 'ai_assistant_configs', ['session_id'], unique=False)
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_project_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_folders_project_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_parent_folder_id'), table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
